rvm/rvm

patchsets/ruby/2.2/head/railsexpress
can you please merge?
otherwise railsexpress head patches will fail against current ruby-2_2 head
=> dropped railsexpress backport-401c8bb as it has been merged to ruby_2_2

scripts/functions/requirements/ubuntu
Hi Michal!
Failed on my Mint 17.1 machine/ubuntu based system, runs fine with the lib installed. Hope that this is the right place :)
Error running '/home/tobi/.rvm/wrappers/ruby-2.2.0@rubinius/rake install --trace',
showing last 15 lines of /home/tobi/.rvm/log/1421001055_rbx-2.4.1/rake.log
4: CXX vm/builtin/list.cpp
In file included from vm/builtin/jit.cpp:7:
/home/tobi/.rvm/src/rbx-2.4.1/vm/llvm/state.hpp:10:10: fatal error: 'llvm/IR/Module.h' file not found
#include <llvm/IR/Module.h>
Cheers,
Tobi
=> Add llvm-dev to rbx requirements

scripts/rvm
Adds a hint to use `rvmsudo` when `GEM_HOME` and `GEM_PATH` aren't set in `sudo` shell.
=> sudo path hint

scripts/functions/requirements/opensuse
Tested on SLES 12 x64. I checked the packages list for everything else we want to install on SLES and it's just libdb that needs a conditional check.
=> Use the right libdb on SLES 12

scripts/functions/installer
The `--path` parameter is not respected when installing (./install) if rvm_path and/or rvm_bin_path is defined in `~/.rvmrc` or `/etc/rvmrc`.
Not sure if it's desirable to ignore the whole rvmrc; is the install script supposed to respect other parameters from rvmrc?
=> Ignore ~/.rvmrc and /etc/rvmrc when --path is specified

scripts/functions/build_requirements
Prevents a possible `__rvm_requirements_run_summary:12: bad math expression: illegal character: "` warning.
=> Remove quotes inside arithmetic expression

scripts/functions/build_config
This prevents an openssl bug where it requires -lz when it's statically linked but it isn't available by default.
For example, this was causing issues with building the puma gem:
```ruby
require 'mkmf'
have_library 'crypto', 'BIO_read'
#>> checking for BIO_read() in -lcrypto... yes
#=> true
have_library 'ssl', 'SSL_CTX_new'
#>> checking for SSL_CTX_new() in -lssl... no
#=> false
have_library 'z'
#>> checking for main() in -lz... yes
#=> true
have_library 'ssl', 'SSL_CTX_new'
#>> checking for SSL_CTX_new() in -lssl... yes
#=> true
```
=> Added -lz to ruby build flags

binscripts/rvm-installer, scripts/functions/cli
Should fix #3213.
Tested with the presence of `gpg2.exe` provided by Gpg4win and `gpg.exe` provided by Cygwin, with and without a stand-in `gpg2.exe` (just a copy of `gpg.exe`) in the Cygwin path. In each case, Gpg4win's version was ignored as desired, and rvm installation proceeded happily.
=> Added some missing ${}s to install scripts

scripts/functions/installer
This greps for the login-shell option in the Default profile of gnome-terminal and sets it, if not already existing. Thus you will never have to set it manually, avoiding the 'RVM is not a function' message
Solves issue #3395
=> Automatically set the login shell option for gnome-terminal

patches/rbx/2.5.2/clean_bundler_environment_before_running_homebrew.diff, patches/rbx/2.5.2/this_can_not_be_null.diff, patchsets/rbx/2.5.2/default
This pull request adds two patches to rubinius 2.5.2, rubinius/rubinius@50aa7356 and d4rky-pl/rubinius@bb2f37b1 to allow them to compile on OS X 10.10 clang and homebrew installed.
=> Add patches to fix Rubinius compilation on OS X. Fixes #3386

scripts/functions/requirements/arch
=> Add forcing 3.5 version of both clang and llvm in Archlinux

patchsets/ruby/2.1.6/railsexpress, patchsets/ruby/2.1/head/railsexpress, patchsets/ruby/2.2.2/railsexpress
There are a lot of fixes scheduled for 2.2.3. This patch adds those to railsexpress 2.2.2.
=> railsexpress: heap dump support and backported fixes for 2.2.2

contrib/unicorn_init.sh
Even when I have specified "RAILS_ENV=production" in my /etc/unicorn/my-app.conf, the previous unicorn_init.sh when deployed in /etc/init.d/ as a service always runs my rails server in development mode.
It turns out that the RAILS_ENV in the /etc/unicorn/my-app.conf was not passed to the unicorn command. This commit fixes that problem.
This commit also set the default environment for the unicorn service is set to development, following rails convention.
This is the second time that I have opened this pull request, as the last pull request failed the CI job for an unrelated reason. I made a tiny improvement, though, for the very rare cases when somebody's rails environment has a space in it such as `RAILS_ENV="with space"`.
=> Respect RAILS_ENV in unicorn service setup. Default to development

.travis.yml
The container-based builds should be faster than the VM-based builds.
http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
=> Container-based travis builds

scripts/functions/requirements/cygwin
The packages `mingw64-i686-gcc` and `mingw64-x86_64-gcc` got renamed and received a `-core` extension
https://cygwin.com/cgi-bin2/package-grep.cgi?grep=mingw64-.*-gcc&arch=x86_64
=> cygwin: package names for mingw64-*-gcc changed

scripts/functions/manage/jruby
See #3457. This handles the case where Maven is installed but it's a version prior to Maven 3.3.1 by using the mvnw wrapper JRuby provides. Closes #3470 and #3499.
=> Use JRuby's ./mvnw to build JRuby 9k+

scripts/functions/requirements/arch
Checks if any known ntp daemon is running before trying to enable it.
Currently known ntp daemons are:
- ntp
- systemd-timesyncd
- openntpd
- chrony
Fixes #3363.
=> Support multiple ntp daemons for arch linux

scripts/alias
Alias was giving an improper syntax in it's error message, it only indicated 2 argument, but it requires 3.
=> Making alias's error message reflect actual usage.

binscripts/rvm-installer
When grep is not installed, RVM installer script misdetects that tar is not installed even if tar is installed.
=> Detect an absence of grep

README
This is a change that goes along with https://github.com/rvm/rvm/pull/3526.
Adds the --64-bit flag to the README which is the option for installing 64-bit rubies (although this is also default behavior).
=> Update README to explicitly indicate --64 flag

scripts/functions/requirements/ubuntu
RVM uses the binaries from Travis CI for its installations.
The binaries for Ubuntu from Travis CI are compiled against libgmp which
means that `-lgmp` is part of the `RbConfig::CONFIG["LIBS"]` and is used
in the compilation of ever C extention in ruby.
If libgmp is not installed, then any installation of any C extension rubygem
will fail when rubygems attempts to make sure that the compiler works.
This is evident by errors such as:
```
vagrant@vagrant-ubuntu-trusty-64:~$ gem install hitimes
Fetching: hitimes-1.2.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
ERROR: Failed to build gem native extension.
/home/vagrant/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151119-7016-spbnuj.rb extconf.rb
checking for clock_gettime() in …
```
=> Add libgmp-dev as an Ubuntu requirement

scripts/functions/requirements/osx_brew
It's deprecated and not supported by our package manager, and 1.8.7-head (I've not tested REE) builds and runs cleanly on modern OS X with OpenSSL 1.0.2f (Homebrew's latest).
=> Remove requirement to build against OpenSSL 0.9.8

scripts/functions/build_requirements_helpers
Fix requirements_fallback_lib_installed to select a dependency version
from the generated list of those available, rather than the first
possible version.
We have this nice list of what is and isn't available on the system for a
given list of fallbacks - surely we should use one of those instead of
forcing the first dependency option (which may or may not be available)?
=> Select an appropriate dependency fallback version for installation

scripts/functions/requirements/osx_fink
Without this change, getrvm utterly fails on OS-X 10.10.5
=> Change to automake1.14 since 1.13 is no longer available

scripts/functions/requirements/ubuntu
Fix for https://github.com/rvm/rvm/issues/3320.
=> Include llvm-dev package as a pre-req when installing rbx-head

.travis.yml
This will make sure that we don't merge changes to `rvm-installer` without updating the GPG signature.
=> Verify GPG signature during Travis CI build

scripts/cd
On Macs, in the default terminal, PROMPT_COMMAND is set to
'update_terminal_cwd;' with the included trailing semi-colon. This is legal
syntax, and currently, the cd script does not handle it gracefully. Reordering
the hooks fixes the problem.
=> Reorder PROMPT_COMMAND hook to prevent error on Mac OS

scripts/functions/environment
This fixes #3655 by avoiding the call to `shell_session_update` if it's not a function.
=> Don't trap with a non-existent command

scripts/functions/rvmrc_project
I'm using zsh + tmux
when the working dir is removed, the $working_dir is going to be "."
which causes the infinite loop while calling __rvm_project_dir_check below.
you can reproduce it easily by using tmux.
1. Let's add an line `echo "loop!!"` to `scripts/functions/rvmrc_project:36`
2. create a dir `/tmp/a`
3. **`cd /tmp/a`**, then run `tmux new-session -s test`
4. use the shortcut to `detach-client`
5. `..; rm -rf a`
6. use the shortcut to `split-window`
7. Now you got an infinite loop
=> avoid infinite loop

config/known, config/known_strings, config/md5, config/sha512
1.7.25 was released a week ago: http://jruby.org/2016/04/14/jruby-1-7-25.html
=> Bump JRuby to 1.7.25

scripts/functions/pkg
this seems to have been looked over in a previous commit, the previous command results in downloading an html redirection page which isn't very useful. to say nothing of the possible security risk.
=> switch another url to https

scripts/functions/requirements/centos
This impacts Fedora where Fedora 24 ships with OpenJDK 1.8.0 only, 1.7.0 is no longer available as a package. Jruby 9.1.2.0 is happy with 1.8.0 so printing an advisory about 1.7.0, which is very difficult to install manually, is misleading.
Presumably this is good to get in now since RHEL and CentOS will update to this soon if they haven't already.
=> Adding tests for OpenJDK 1.8.0 for Jruby + CentOS/Fedora

scripts/functions/rvmrc_warning
It looks like be6f83626c67c11aea920d522b114a15f9e2b786 introduced an error, as the option is `allGemfiles`, not `all Gemfiles`.  
Source: https://github.com/rvm/rvm/blob/9be6aeb257c3cc68589ae01b7364a6b704acc428/scripts/functions/rvmrc_warning#L30
Error message I encountered:
=> Fix error message about ignoring all Gemfiles

scripts/notes
references #1351. I just ran into this issue and think the solution could be more clear as shown in the issue $PATH needs to prepended, but the message says that #PATH  needs to be appended
* changes #PATH to $PATH to be more clear what needs to be done
* changes append to prepend since $PATH needs to be prepended
=> improves warning message for when PATH= is set without $PATH

scripts/functions/detect_system
Binaries built for CentOS should be compatible to run on Red Hat Enterprise Linux of the same version. I see no benefit to build them again.
It would be nice if rvm adds RHEL to the build chain. But using CentOS binaries is IMO also a good approach.
This pull would partially fix #3735
=> use CentOS binaries for RHEL

binscripts/rvm-installer, scripts/functions/cli, scripts/functions/requirements/cygwin
Other versions installed outside of Cygwin do not understand Cygwin paths and fail on verifying downloaded files.
Fixes #3623
=> Enforce usage of gpg coming from Cygwin on Windows

scripts/functions/env
Plus fixed Sublime Text's highligting.
Unset is called with these envvar names:
```
$     set |
>       __rvm_awk -F"=" 'BEGIN{v=0;} /^[a-zA-Z_][a-zA-Z0-9_]*=/{v=1;} v==1&&$2~/^['\''\$]/{v=2;}
>         v==1&&$2~/^\(/{v=3;} v==2&&/'\''$/&&!/'\'\''$/{v=1;} v==3&&/\)$/{v=1;} v{print;} v==1{v=0;}' |
>       __rvm_awk -F"=" '/^[^ ]*(RUBY|GEM|IRB|gem|rubies|rvm)[^ ]*=/ {print $1} /^[^ ]*=.*rvm/ {print $1}' |
>       __rvm_grep -vE "^PROMPT|^prompt|^PS|^BASH_SOURCE"
GEM_HOME
GEM_HOME
GEM_PATH
GEM_PATH
IRBRC
IRBRC
MY_RUBY_HOME
MY_RUBY_HOME
PATH
RUBY_VERSION
chpwd_functions
file
rvm_bin_path
rvm_bin_path
rvm_ignore_rvmrc
rvm_path
rvm_path
rvm_prefix
rvm_rubygems_path
rvm_rubygems_path
rvm_saved_env
rvm_version
rvmrc
rvmrc
```
So, $PATH was empty after __rvm_unload.
Now it should be fine.
=> $PATH become empty after __rvm_unload executed. 

CHANGELOG.md, scripts/functions/build_config
RVM can automatically detect number of available threads.
* remove hardcoded `-j3`
=> Don't hard code number of compile threads

CHANGELOG.md, scripts/functions/requirements/osx_brew
=> Remove incompatible version of openssl098

CHANGELOG.md, binscripts/rvm-installer, scripts/functions/cli, scripts/functions/requirements/osx_brew
Drop GPG v1 support, as it has trouble with fetching keys from hkp://keys.gnupg.net.
Added note highlighting issues with GPG 2.1.17
Fixes #3544
=> Drop GPG v1 support, as it has trouble with fetching keys

CHANGELOG.md, scripts/functions/utility_system
Filtering Travis binaries for OSX for non-travis env (they are statically linked and not movable)
Fixes #3690, #3582, #3861
=> Filtering Travis binaries for OSX for non-travis env

scripts/functions/requirements/solus
Small fix for Solus. The package kernel-libc-devel package has been renamed to kernel-headers and causes rvm install to fail because kernel-libc-devel cannot be found by the package manager. The package is also not required and can be removed
* Remove kernel-libc-devel dependency on Solus
=> Remove kernel-libc-devel dependency on Solus

CHANGELOG.md, scripts/extras/rvm.fish
Fix related to [fish-shell\#3809](https://github.com/fish-shell/fish-shell/issues/3809) .
* changed `eval` to `source` to make `rvm.fish` compatible with Fish v2.5.0
More details about mentioned issue in following discussions:
* syl20bnr/spacemacs/issues/4755 (the issue i've initially ran into) 
* purcell/exec-path-from-shell/issues/56
* fish-shell/fish-shell/issues/3809 (the solution implemented was proposed in this thread)
Similar PR submited to oh-my-fish/plugin-rvm: oh-my-fish/plugin-rvm/pull/10
=> Changed eval to source for fish v2.5.0 compatibility

CHANGELOG.md, scripts/functions/requirements/opensuse
OpenSSL vs libressl conflict installing ruby-2.4.0 on openSUSE Tumbleweed
Fixes #3906
=> OpenSSL vs libressl conflict installing ruby-2.4.0 on openSUSE

CHANGELOG.md, binscripts/rvm-installer
Fixes #3832.
* Don't try to parse mounted filesystem table to detect partitions mounted `noexec`
* Create a temporary script and try to execute it to actually test if scripts are runnable from the target location
=> Use actual executable test instead of mount|grep noexec

CHANGELOG.md, scripts/notes
Add a check for the `.`  source syntax in the bash startup files before warning about `.profile` not being sourced. 
Fixes #3960
* Use a regular expression that also detects the use of `.` as well as `source`
* Improved the wording of the warning a little
=> Detect `.` as an alternative to `source` in bash profile warning

bin/rvm-prompt
When using the unicode flag(†), render numbers for Ruby version 2.3.* and 2.4.* instead of treating these versions as unknown.
* Added extra output options for the `rvm-prompt` helper script.
(†): `~/.rvm/bin/rvm-prompt unicode`
=> Support Ruby 2.3 and 2.4 in rvm-prompt

CHANGELOG.md, scripts/functions/manage/base_remove
**Preconditions:**
```
$ rvm install jruby-1.7.27
```
**Steps to reproduce:**
```
$ rvm remove jruby
```
**Expected result:**
```
jruby-1.7.26 - #removing rubies/jruby-1.7.26..
...
```
**Actual result:**
```
jruby-9.1.8.0 - #already gone
```
**Temporary solution:**
```
$ rvm remove jruby --fuzzy
```
**Final solution implemented in this PR:**
No need to use `--fuzzy` switch.
=> Use fuzzy version match for `rvm remove`

CHANGELOG.md, scripts/functions/cli
some commands (like `rvm list known`) display error messages like `command not found: __rvm_remote_version` or `__rvm_cli_autoupdate_version_old:2: command not found: __rvm_remote_version`
Looking into code, the actual function name is `__rvm_version_remote`, so this commit fixes that reference.  I only found the bad reference in a single location.
It doesn't seem to cause any significant harm, but fixing this will clean up an error message that appears in the terminal when some commands are run.
I didn't find an existing github issue for this.
* Fix a function reference to eliminate an error message
=> Command not found `__rvm_remote_version` error

CHANGELOG.md, scripts/functions/environment
Fixes #4072 .
* Source `scripts/functions/version` instead of `scripts/version` at `scripts/environment`
The modification of cc758aa seems to be insufficient.
When run `source "/path/to/.rvm/scripts/rvm"`, the following warning will be output:
```
WARNING:
Could not source '/path/to/.rvm/scripts/version' as file does not exist.
RVM will likely not work as expected.
```
The warning will resolved by this patch.
I hope this helps.
=> Fix path of version script in `environment`

CHANGELOG.md, scripts/cd
This change introduces a backwards compatible fix, r[ecommended by
the zsh maintainers](http://zsh.sourceforge.net/releases.html). Our cd(), pushd() and popd() are now defined
properly.
* Small update to how shell init happens in zsh, to fix a bug under 5.4.1
=> zsh 5.4.1 changes how alias expansion during function def works

CHANGELOG.md, scripts/base, scripts/functions/environment, scripts/functions/support, scripts/rvm
Fixes #4013.
Allows running RVM shell function in Bash with `set -o nounset`
=> Disable nounset for rvm run, fix #4013

CHANGELOG.md, patches/ruby/2.3.2/random_c_using_NR_prefix.patch
Getting the following message when trying to build Ruby 2.3.2:
```
ruby-2.3.2 - #extracting ruby-2.3.2 to /home/rof/.rvm/src/ruby-2.3.2....
ruby-2.3.2 - #applying patch /home/rof/.rvm/patches/ruby/ruby_2_3_gcc7.patch.
Patch 'random_c_using_NR_prefix' not found.
There has been an error applying the specified patches. Halting the installation.
```
It looks like `random_c_using_NR_prefix.patch` was added in #4048, but did not get included for 2.3.2.
=> Add missing random.c patch for Ruby 2.3.2

CHANGELOG.md, patchsets/ruby/2.2.8/railsexpress, patchsets/ruby/2.3.5/railsexpress, patchsets/ruby/2.4.2/railsexpress
Latest railsexpress patches.
Patches also fix the 2.3.5 and 2.4.2 failure to compile and link against libgmp.
=> railsexpress patches for 2.2.8, 2.3.5 and 2.4.2

CHANGELOG.md, scripts/functions/requirements/centos, scripts/functions/requirements/redhat
Ruby supports embedded libyaml since 2.0.0, no need to require superfluous and buggy instructions to add it.
This can pose security risk for not updated libyaml - but it should be Ruby's responsibility to inform users about it!
Fixes #2998
Update #3194
Deprecate/fix #3191
Deprecate/fix #3207
Partially fixes #3304
=> Use Ruby's bundled libyaml

CHANGELOG.md, scripts/functions/requirements/ubuntu
Starting from Ubuntu 16.10 the correct package name is `libreadline-dev`
Fixes #4172
=> libreadline6-dev is not a valid Ubuntu 16.10 package

CHANGELOG.md, scripts/functions/requirements/opensuse
Fixes https://github.com/rvm/rvm/issues/4178
* Use the proper version of libdb in OpenSuSE tumbleweed
=> Require libdb-4.8 for OpenSuSE Tumbleweed

CHANGELOG.md, scripts/functions/requirements/arch, scripts/functions/requirements/centos, scripts/functions/requirements/cygwin, scripts/functions/requirements/debian, scripts/functions/requirements/dragonfly, scripts/functions/requirements/freebsd, scripts/functions/requirements/gentoo, scripts/functions/requirements/netbsd, scripts/functions/requirements/openbsd, scripts/functions/requirements/openindiana, scripts/functions/requirements/openmandriva, scripts/functions/requirements/opensuse, scripts/functions/requirements/osx_brew, scripts/functions/requirements/osx_fink, scripts/functions/requirements/osx_port, scripts/functions/requirements/pclinuxos, scripts/functions/requirements/rvm_pkg, scripts/functions/requirements/smartos, scripts/functions/requirements/smf, scripts/functions/requirements/solaris, scripts/functions/requirements/solus, scripts/functions/requirements/synology, scripts/functions/requirements/unknown
=> Require make for JRuby 9

CHANGELOG.md, scripts/functions/requirements/osx_port
Fixes #4208
* When installing Ruby on OSX with MacPorts, don't try and install OpenSSL if LibreSSL is already installed.
=> Fix installing Ruby with LibreSSL and MacPorts (Issue #4208)

CHANGELOG.md, scripts/functions/requirements/debian
Fixes #3675
See https://github.com/rvm/rvm/issues/3675#issuecomment-344501157
=> Fix invalid `libgmp3-dev` requirement for Debian

CHANGELOG.md, scripts/functions/requirements/fedora
=> Ensure compat-openssl10-devel is not installed for Fedora 26+ and Ruby 2.4+

CHANGELOG.md, patchsets/ruby/2.2.9/railsexpress, patchsets/ruby/2.3.6/railsexpress, patchsets/ruby/2.4.3/railsexpress, patchsets/ruby/head/railsexpress
I'd like to support railsexpress patches for ruby head.
=> railsexpress patches for ruby trunk, 2.2.9, 2.3.6, and 2.4.3

config/db
Follow-up from #4265.
This will make RVM install Ruby 2.5.0 when user do `rvm install ruby`.
=> Set recommended MRI version to 2.5.0

CHANGELOG.md, patchsets/ruby/2.5.0/railsexpress
See https://bugs.ruby-lang.org/issues/14248
=> Fix fd_mask detection on OS X for Ruby 2.5.0

CHANGELOG.md, scripts/functions/gemset
Fix installing rubygems 2.7
- move only new cached gems to globalcache
- move creating @global link before installing rubygems
=> Fix installing rubygems 2.7

CHANGELOG.md, scripts/functions/group
Fixes #4296 .
* Use an improved regular expression to avoid matching group names that contain the string `rvm`
=> Correctly look for rvm group in /etc/group.

CHANGELOG.md, scripts/functions/requirements/debian, scripts/functions/requirements/ubuntu
=> Add support for installing Ruby <2.4 on Ubuntu 17.10+

CHANGELOG.md, patchsets/ruby/2.2.10/railsexpress, patchsets/ruby/2.3.7/railsexpress, patchsets/ruby/2.4.4/railsexpress, patchsets/ruby/2.5.1/railsexpress
These are for the security based latest ruby releases.
=> RailsExpress patchsets for 2.2.10, 2.3.7, 2.4.4 and 2.5.1

CHANGELOG.md, scripts/functions/installer
Aliases cleanup was issuing unnecessary warning about missing config/alias
Added check for file existence to avoid the warning
=> Avoid unnecessary install warning

CHANGELOG.md, help/install.md
Partially fixes #4312.
Adds documentation in `rvm help install` for:
* (OSX) `--universal`
* `--arch` | `--archflags`
* (rbx & jruby) `--1.8` | `--1.9` | `--2.0` | `--2.1` | `--18` | `--19` | `--20` | `--21`  
* `--clang` 
* `--disable-llvm` | `--disable-jit` | `--enable-llvm` | `--enable-jit`  
* `--with-arch` 
* `--`
* `--with-*` | `--without-*`
* `--enable-*` | `--disable-*`
* `-E` | `--env`
* `-M`
* `--rdoc` | `--yard`
* `--url` | `--repository` | `--repo` 
* `--branch`
* `--sha`    
* `--trace` 
* `--proxy`
Reformats some sections / subheadings and realigns a few bits.
=> Document additional rvm install options

CHANGELOG.md, patches/ruby/2.2.10/fix_installing_bundled_gems.patch, patches/ruby/2.2.5/fix_installing_bundled_gems.patch, patches/ruby/2.2.6/fix_installing_bundled_gems.patch, patches/ruby/2.2.7/fix_installing_bundled_gems.patch, patches/ruby/2.2.8/fix_installing_bundled_gems.patch, patches/ruby/2.2.9/fix_installing_bundled_gems.patch, patchsets/ruby/2.2.10/default, patchsets/ruby/2.2.6/default, patchsets/ruby/2.2.7/default, patchsets/ruby/2.2.8/default, patchsets/ruby/2.2.9/default
Copied the ruby-2.2.4 patch to ruby-2.2.5 to ruby-2.2.10.
Fixes #4358.
=> Extend ruby 798 patch to ruby 2.2 versions that don't have it.

scripts/functions/manage/truffleruby
* So necessary packages get installed and the per-distribution logic gets triggered.
I missed the fact `__rvm_setup_compile_environment()` is the function triggering the per-distribution logic to install packages in https://github.com/rvm/rvm/pull/4406.
cc @mpapis @havenwood 
Relates to #4297.
=> Call __rvm_setup_compile_environment() for TruffleRuby

CHANGELOG.md, gemsets/truffleruby/global.gems
* Fixes #4408.
* Avoid changing the behavior of standard Ruby executables.
* No need to install rake, it is part of the standard library.
This seems the most straightforward solution to #4408.
`rubygems-bundler` and its dependencies `executable-hooks` and `bundler-unload` are no longer installed by RVM for TruffleRuby.
This seems saner to me, as `rake`, `ri`, `rdoc`, etc behave like they do outside of RVM and are not changed to load Bundler or have a broken shebang.
This means as TruffleRuby developers we can support these executables and rely on less magic for users (no special RVM-specific behavior).
That said, I'm open to other solutions, but we need to fix this quickly.
As a side note, `gem-wrappers` itself is fine as it just generates some extra files outside of `PATH`, so I kept …
=> Do not use rubygems-bundler on TruffleRuby

scripts/functions/requirements/osx_brew
* requirements_osx_brew_after() expects some global variables to be set,
notably $brew_libs, $brew_libs_conf and $brew_openssl_package.
@havenwood told me the logic on macOS for TruffleRuby wasn't quite working as expected.
Now TruffleRuby uses the same logic as MRI/Rubinius, as there are complex dependencies between functions due to global variables used within `requirements_osx_brew_after()`.
This installs a few more packages than needed (`autoconf`, `automake`), but for now this seems the safer and simpler fix.
Relates to #4297.
=> Reuse the logic for MRI/Rubinius for TruffleRuby for requirements on macOS

CHANGELOG.md, scripts/functions/hooks/jruby
JRuby 9+ runs nailgun with an org.jruby.main.NailServerMain wrapper.
JRuby 1.7.x calls com.martiansoftware.nailgun.NGServer directly.
Check for both when attempting to see if nailgun is running.
Fixes #4089.
=> Fix nailgun detection on JRuby 9+

CHANGELOG.md, config/db, scripts/functions/utility, scripts/functions/utility_system
* Switch download URL to Maven address.
* Fix structure of tarball filename.
* Allow "HTTP/2 200" format in curl results.
Fixes #4223.
=> Updates and fixes to switch to new JRuby binary URL.

CHANGELOG.md, scripts/functions/manage/truffleruby
* TruffleRuby already checks later and looks up more paths to find the LLVM executables clang and opt.
(TruffleRuby also looks up in Homebrew and MacPorts directories on macOS).
* See https://github.com/oracle/truffleruby/issues/1386 for details.
So this logic is redundant because per-platform checks for installing LLVM are already in RVM and TruffleRuby itself checks if `clang` & `opt` are available when it needs to compile C extensions.
It's also needlessly restrictive for Homebrew and MacPorts (forcing the LLVM executables to be in `PATH`), so it needs to be removed.
cc @havenwood
=> Remove early check for LLVM with TruffleRuby

help/index.txt
* Removes 'usage' command as its deprecated and returns such message
* did not know so much what to do there so feel free to edit or refuse this pull and use the data/idea behind it.
=> updates help index

CHANGELOG.md, patches/ruby/2.5.0/libressl_2_7.patch, patches/ruby/2.5.1/libressl_2_7.patch, patchsets/ruby/2.5.0/default, patchsets/ruby/2.5.1/default
Based on https://github.com/ruby/openssl/issues/192
=> Fix Ruby 2.5.0 and 2.5.1 build with LibreSSL 2.7.0

.travis.yml
Runs the test added in https://github.com/rvm/rvm-test/pull/26 in rvm/rvm's CI.
Relates to #4297 and https://github.com/rvm/rvm/pull/4456#issuecomment-432487811.
cc @mpapis @pkuczynski @havenwood
=> Update rvm-test and test installing TruffleRuby

.travis.yml
* So we can test installing packages with rvm autolibs.
* Containers are being deprecated in TravisCI:
https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
cc @pkuczynski
=> Allow sudo in TravisCI

README.md
Hi, I'm making updates for Open Collective. This pull request fixes backers and sponsors from your Open Collective https://opencollective.com/rvm and adds the contributor image❤️
It fixes placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look …
=> Fix Open Collective

docs/gpg.md
`gpg2 --verify rvm-installer.asc` would do the right thing only if the file actually contained a detached signature.
Use explicit and robust `gpg2 --verify rvm-installer.asc rvm-installer` instead.
=> Improve gpg signature verification docs

.travis.yml
For some reason Travis is unable to verify rvm-installer due to missing key. This should fix our failsafe build job to make sure we don't break rvm-installer.
See https://travis-ci.org/rvm/rvm/jobs/468465092
=> Fix Travis build on GPG keys

.travis.yml
This will silence 2,000 lines of output noise from Travis log.
This will hopefully help us trace why the build is failing.
See https://travis-ci.org/rvm/rvm/jobs/468854212#L173
=> Add `brew update` step for macOS

CHANGELOG.md, scripts/functions/requirements/osx_brew
Improves #4402
* Add check for CommandLineTools that uses newer package name:
pkgutil --pkg-info com.apple.pkg.CLTools_Executables
When XCode is not installed, the __rvm_detect_xcode_version_at_least
check from osx_brew falls back to __CLT_version_at_least 4.6.0 that
tries to detect the version of command line tools. The command it uses:
pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI is outdated.
That package doesn't exist in Mojave and this change adds another
fallback that uses the new package name.
Before the change any commands that required building ruby was failing
with:
rvm install 2.5.3
...
Xcode version older than 4.6.2 installed, download and install newer version from:
...
Verified that this solved the issue by successfully executing: …
=> Fix Command Line Tools version detection on MacOS 10.14.1

scripts/functions/cli
Fixes #4535.
This resolves an issue where the local version was being checked for inequality, rather than less than comparison, with the online version.
=> Fix comparison of local and online stable versions

CHANGELOG.md, scripts/functions/requirements/centos
Seems that CentOS needs some version of ruby to be installed to compile new ruby. This PR adds `ruby` dependency.
Fixes issue: `executable host ruby is required. use --with-baseruby option.`
Fixes #4529
=> Add system ruby as dependency for CentOS

scripts/functions/requirements/osx_brew
Fixes a regression added in #4556 (https://github.com/rvm/rvm/pull/4556/commits/f4ee90e6d90faf08ad9c76b4c21e72213bca4fd8). Looks like this was simply over looked.
* Pass argument all the way through to `requirements_osx_brew_define_openssl()`
Possibly related: #4562
=> Fix macOS openssl requirement gathering with Homebrew

scripts/functions/environment
* Don't spoil environment with '_system_*' variables
I find it quite annoying to have strange env variables in CI environment where rvm is installed and loaded.
Another question is why they don't have 'rvm' prefix.
=> Don't spoil environment with '_system_*' variables

CHANGELOG.md, scripts/functions/requirements/ubuntu
* Install libssl1.0-dev for version 1.8 of Ruby on Ubuntu linux
=> Install libssl1.0-dev for version 1.8 of Ruby on Ubuntu linux

update-truffleruby.rb
This automates adding a new TruffleRuby version in RVM, and avoids copy-paste errors.
Where should I place the script?
For now, I added it at the root of the repo like e.g., `update-remote.sh`.
cc @pkuczynski @havenwood @nirvdrum
=> Add script to automatically register a new TruffleRuby release in RVM

.travis.yml
As seen in https://github.com/rvm/rvm/issues/4561#issuecomment-450678661, it happens that the CI of RVM passes, yet `rvm: truffleruby` doesn't work in TravisCI.
So this PR adds a test using `rvm: truffleruby` in RVM's `.travis.yml`.
This is exactly what people testing their Ruby library on TravisCI will use, and so tests one important use-case where RVM is used.
cc @pkuczynski
=> Test TruffleRuby in TravisCI in RVM's .travis.yml

docs/release-procedure.md
This tiny PR fixes a few broken links in the release procedure documentation.  Currently the links take you to GitHub's 404 page.
=> Fixes broken links to VERSION and CHANGELOG.md in release-procedure.md

.travis.yml
* See https://github.com/rvm/rvm/issues/4579
I'd like the build to be green, to avoid regressions (e.g., #4609).
Another option is completely removing tests on macOS, but many tests pass:
https://github.com/rvm/rvm/issues/4579#issuecomment-462966466
cc @pkuczynski
=> Allow failures on macOS until the CI is fixed on macOS

.travis.yml
Fixes #4579.
This PR makes the macOS CI on TravisCI green.
For that, it removes very slow (5min/job vs 20-40min) and unreliable calls to Homebrew by using `rvm autolibs read-only`. Without that, RVM would call to Homebrew and update many packages, which would take a very long time and lead to build failures (#4579).
In practice, it is clear TravisCI macOS machines already have all the necessary dependencies to test RVM and install the tested Ruby versions.
I think we should merge this because it's more valuable to test the rest of the logic (everything except `autolibs`) on macOS, than having a failing CI and issues potentially piling up.
cc @pkuczynski @havenwood
=> Fix macOS CI

scripts/functions/gemset
Tiny wording change. It is unclear at that moment if its one or multiple gems or anything else that made the command fail. The message now is however better than the mix of singular and plural.
=> Fix wording (this gems -> these gems)

binscripts/rvm-installer
`__rvm_setup_compile_environment_flags_threads()` in scripts/functions/build_config auto-detects the number of threads to use
* remove the hardcoded number of jobs from rvm-installer so that it will auto detect and build with as many threads as it can
Related: #3856
=> rvm-installer: remove hardcoded number of jobs

CHANGELOG.md, scripts/functions/requirements/cygwin
Fixes #4684
updated openssl-devel requirement for Cygwin to libssl-devel
=> Update openssl-devel to libssl-devel for Cygwin

CHANGELOG.md, scripts/functions/rvmrc_set
This pull request fixes the rvm version validation.
Steps to reproduce:
1) install the latest version of rvm 1.29.8
2) Generate the .rvmrc  using "rvm rvmrc create" in an empty directory
3) Uncomment the part where it says "Uncomment the following lines if you want to verify rvm version per project" and run it and you will get an error message like this 
$ bash .rvmrc
.rvmrc: line 13: __rvm_awk: command not found
After fixing removing the extra  __rvm_ before awk and setting 
rvmrc_rvm_version="1.30.8 (latest)
then I got this 
$ bash  .rvmrc
This .rvmrc file requires at least RVM 1.30.8 (latest), aborting loading.
.rvmrc: line 16: return: can only `return' from a function or sourced script
After this fix, this is the output
$ bash  .rvmrc
This .rvmrc file requires at least RVM 1.30.8 …
=> Fix the rvm version checking

.travis.yml
This is needed, because the Travis CI apt addon installs packages with
--no-install-recommends and dirmngr is a recommended package for gnupg2.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845720 for discussion.
No Changelog update since this only concerns CI.
=> Install missing dirmngr for GPG signature test

CHANGELOG.md, scripts/functions/utility_system
If the check for Travis CI binaries returned false – as is always the case outside of Travis CI – the code could go into an endless loop, because is was continued before the iterator was incremented.
=> Fix endless loop on macOS when listing remotes

CHANGELOG.md, scripts/functions/gemset
This removes any occurrence of `--no-document`, `--no-ri` and `--no-rdoc` from `rvm_gem_options` when merging with the auto-detected `install_params` to avoid duplicate, deprecated or incompatible options.
This should fix the current test failures for ruby-1.8.7 under Xenial on Travis CI, where the default Travis `~/.rvmrc` contains `rvm_gem_options='--no-ri --no-rdoc --no-document'` breaking rvm gem installs with rubygems 1.8.25 which does not yet support the `--no-document` option.
=> Filter redundant/incompatible rvm_gem_options

CHANGELOG.md, config/db, scripts/functions/manage/base_install, scripts/functions/selector_interpreters, scripts/functions/utility, scripts/functions/utility_system
TruffleRuby is a mix of "source" and "binary" Ruby in RVM terminology (https://github.com/rvm/rvm/issues/4297#issuecomment-397843910 for details).
So originally I added the "from source" code (#4406), and then later the "binary" code (#4456) as that's what TravisCI normally uses. However, the TravisCI code had to be modified anyway, so there is no need for handling TruffleRuby as a "binary" Ruby in RVM anymore.
I want to remove the code (which I added) for handling TruffleRuby as a "binary" Ruby. It's duplicating a fair bit of code, it does not work well, and introduces more ways to fail.
For example, one part which is fragile with binary rubies is for instance downloading with a timeout and trying all the remotes. I don't want that, I know exactly the one URL where TruffleRuby should be …
=> Always use the "from source" installation path for TruffleRuby

CHANGELOG.md, scripts/functions/env
Fixes # .
I'm running Ubuntu with RVM installed using the PPA.  The rvm_path is set to ```/usr/share/rvm``` however my gems (by default) are installed to ```~/.rvm/gems```.  As a result, when I cd to different directories my PATH gets longer and longer because the gems paths aren't removed.
* When removing directories from PATH in ```__rvm_remove_rvm_from_path``` also remove directories with ```rvm_gems_path``` as a prefix.
=> Remove rvm_gems_path from PATH as part of __rvm_remove_rvm_from_path

CHANGELOG.md, scripts/functions/checksum
Fix condition to only try `curl` if no checksum is found
* This would cause checksum checks to fail even if checksums exist in the config files, as long as the given URL does not exist.
* This bug was introduced by #4650
Only try to get the checksum from the network after checking the config files (avoiding extra `curl` queries if not needed).
This notably fixes the checksum check for TruffleRuby.
cc @pkuczynski @mpapis
=> Fix checksum check condition to not try url if already found in config files

CHANGELOG.md, scripts/functions/checksum
Now that checksums work again with #4707, I noticed new checksum mismatches, for example
https://travis-ci.org/rvm/rvm/jobs/547675787
Which seems to be the reason the CI currently fails on macOS.
In TravisCI, binary rubies from TravisCI are used on macOS, which meant https://rubies.travis-ci.org/osx/10.13/x86_64/ruby-2.3.4.tar.bz2?rvm=1.29.8-next.md5 would be tried.
And actually, even fixing that to https://rubies.travis-ci.org/osx/10.13/x86_64/ruby-2.3.4.tar.bz2.md5, that still downloads the full archive, not a checksum file.
So let's not assume `"#{archive_url}.md5"` always downloads a checksum file, but only do it for Rubinius which needs it (#4650).
Downloading a checksum from the same location as the archive seems also less good from a security point of view, so limiting that to the …
=> Fix checksums part two: only check URL checksums for Rubinius

CHANGELOG.md, binscripts/rvm-installer
See https://travis-ci.community/t/rvm-tries-to-download-blank-version-of-itself/3972
I believe this happens if `__rvm_curl -s https://api.github.com/repos/rvm/rvm/tags` fails -- then the output is blank and `_version` in `install_release()` gets set to nothing.
* Don't ignore a possible error on repo tags fetch
=> Handle an error on tags fetch

CHANGELOG.md, binscripts/rvm-installer
Support for Bitbucket REST API v1 had been dropped.  This fix ensures that if GitHub returns a 403, the Bitbucket fallback can save the day.
* Fix rvm-installer's mechanism for fetching RVM tags from Bitbucket.
_This is increasingly important when occasional 403 / api-rate-limiting issues occur when interacting with GitHub.  This is currently happening frequently on Travis-CI._
=> Fix installer fetching RVM tags from Bitbucket

CHANGELOG.md, scripts/functions/gemset, scripts/functions/support
This is an addendum on #4282 for ZSH and possibly other shells.
The current version works fine on bash when `alias ls='something-not-ls'` but on zsh `alias ls='something-not-ls'` is called it currently fails.
It also fixes another `ls` command invocation in `is_gem_installed()`. 
Where `/bin/ls` is installed, this is used instead of the terminals `ls` short command. Otherwise it defaults to the shell sessions `ls` alias if it doesn't find it.
This can be helpful to make sure the default command doesn't have extra arguments.
This was my first attempt and I was able to get rid of the bug, but I think it might be worth it to move the `_ls_command` command out of the function.
=> Ignore aliases when using `ls` command

CHANGELOG.md, scripts/functions/environment
Fixes #4721.
* Export more shell functions which cause the subshell to choke.
=> Export more shell functions which cause the subshell to choke

CHANGELOG.md, scripts/functions/utility
Fixes #4759 
* Adds a check and returns if __rvm_remove_from_path is called with "/*"
=> Guard to prevent removal of the entire path in __rvm_remove_from_path

.travis.yml, CHANGELOG.md, gemsets/truffleruby/global.gems, rvm-test/long/truffleruby_comment_test.sh, scripts/functions/manage/truffleruby
Fixes #4765
* Add tests for `ruby -S bundle` for TruffleRuby (failing originally, see [this run](https://travis-ci.org/eregon/rvm/builds/576230778))
* Do not install rubygems-bundler for TruffleRuby
* Add a post-install message about rubygems-bundler
=> Add tests for ruby -S bundle for TruffleRuby and do not install rubygems-bundler by default

CHANGELOG.md, patchsets/ruby/2.4.6/railsexpress, patchsets/ruby/2.5.6/railsexpress, patchsets/ruby/2.6.4/railsexpress, patchsets/ruby/2.6/head/railsexpress
This PR provides rails express patches for MRI version 2.6.4, 2.5.6 and 2.4.6.
Can you please merge?
=> added railsexpress patches for 2.4.6, 2.5.6 and 2.6.4

CHANGELOG.md, patchsets/ruby/2.6.4/railsexpress
See https://bugs.ruby-lang.org/issues/16136
=> Fix string corruption bug on railsexpress ruby 2.6.4

CHANGELOG.md, config/db, patches/ruby/2.6.4/fix_string_corruption.patch, patchsets/ruby/2.6.4/default
This patches the Ruby 2.6.4 string corruption bug by default for Ruby 2.6.4.
https://bugs.ruby-lang.org/issues/16136
=> Patch the 2.6.4 string corruption bug

CHANGELOG.md, patchsets/ruby/2.4.9/railsexpress, patchsets/ruby/2.5.7/railsexpress, patchsets/ruby/2.6.5/railsexpress, patchsets/ruby/2.6/head/railsexpress
Railsexpress patches for 2.4.9, 2.5.7 and 2.6.5
=> Add railsexpress patches for ruby 2.4.9, 2.5.7 and 2.6.5

CHANGELOG.md, scripts/functions/gemset
Run all JRuby commands from gemset down using --dev flag. This reduces gemset install
time substantially (50.9s -> 40.5s locally).  The rationale
for this change is that short-running JRuby processes should use --dev because
it disables a bunch of optimizations and essentially just runs using the
startup interpreter.  This hurts eventual performance but it also speeds up
short-lived processes.
I do not think I did this quite right but I put it in as a starting point.
mpapis helped me find the proper place but I need guidance on proper code
itself.
=> Run all JRuby commands from gemset down using --dev flag.  This reduces

CHANGELOG.md, scripts/functions/requirements/arch, scripts/functions/requirements/centos, scripts/functions/requirements/debian, scripts/functions/requirements/dragonfly, scripts/functions/requirements/fedora_dnf, scripts/functions/requirements/gentoo, scripts/functions/requirements/opensuse, scripts/functions/requirements/osx_brew, scripts/functions/requirements/osx_fink, scripts/functions/requirements/osx_port, scripts/functions/requirements/pclinuxos, update-truffleruby.rb
* TruffleRuby 19.3+ uses an internal LLVM toolchain and no longer depends on LLVM.
* The full dependencies are listed at
https://github.com/oracle/truffleruby/blob/master/README.md#dependencies
* Previous versions of TruffleRuby detect if LLVM is missing and print
a nice error message, so it is not an issue to remove the dependency
for older versions.
Fixes https://github.com/oracle/truffleruby/issues/1820.
=> Update TruffleRuby dependencies

CHANGELOG.md, scripts/functions/manage/base_fetch
* Use ruby.git master instead of trunk
* In May, ruby.git's trunk branch was renamed to master. Currently trunk was mirrored from master, but it'll be deleted on Jan 1st, 2020. https://bugs.ruby-lang.org/issues/15843
* Therefore rvm should stop referring to ruby.git's trunk branch.
=> Use ruby.git master instead of trunk

CHANGELOG.md, rvm-test/long/truffleruby_comment_test.sh, scripts/functions/manage/base_fetch, scripts/functions/selector_interpreters
* Uses the latest nightly build, which is automatically built.
* I checked in Docker and it works well with `rvm install truffleruby-head`.
cc @gogainda @deepj
Ref: https://github.com/oracle/truffleruby/issues/1483 https://github.com/oracle/truffleruby/issues/1903
=> Add support for truffleruby-head

CHANGELOG.md, scripts/functions/cli
* Previously, using latest RVM would show:
```
Warning, new version of rvm available '1.29.9', you are using older version '1.29.9-next'.
You can disable this warning with:   echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable auto-update with:     echo rvm_autoupdate_flag=2 >> ~/.rvmrc
You can update manually with:        rvm get VERSION                         (e.g. 'rvm get stable')
```
Which seems clearly a bug.
=> Do not warn if using a development version newer than the latest release

CHANGELOG.md, patchsets/ruby/2.5.8/railsexpress, patchsets/ruby/2.6.6/railsexpress, patchsets/ruby/2.7.1/railsexpress, patchsets/ruby/2.7/head/railsexpress
Railsexpress patches for 2.5.8, 2.6.6 and 2.7.1.
Can you please merge?
=> Railsexpress patches for 2.5.8, 2.6.6 and 2.7.1

CHANGELOG.md, config/md5, config/remote, config/sha512
Fixes #4904. Binaries already uploaded.
* Ubuntu 18.04 x64 binaries for  2.4.10, 2.5.8, 2.6.6 and 2.7.1
=> Ubuntu 18.04 binaries for 2.4.10, 2.5.8, 2.6.6 and 2.7.1 (#4904)

CHANGELOG.md, scripts/functions/requirements/debian
* Use an old version 1.8* in Debian 9 using lib SSL 1.0
=> Use libssl-1.0 to install Ruby 1.8 on Debian 9

CHANGELOG.md, scripts/functions/build_config
* Fixed check for ruby 1.9.3+ to include ruby-3
=> Add ruby-3 to the list of available binary builds

CHANGELOG.md, config/md5, config/remote, config/sha512
Linux x64 binaries for:
- Ubuntu 14.04, 16.04, 18.04, 19.10, 20.04
- Oracle Linux 7
- Amazon Linux 2, 2018.03
- Centos 7, 8
- Debian 8, 9, 10
=> Added ruby 3.0.0-preview1 x64 binaries for linux systems

CHANGELOG.md, config/md5, config/remote, config/sha512
- Amazon Linux 2, 2018.03
- Centos 6, 7, 8
- Debian 8, 9, 10
- Oracle Linux 7
- Ubuntu 14.04, 16.04, 18.04, 19.10, 20.04
=> Added ruby 2.7.2 x64 binaries for linux systems

scripts/functions/selector_parse
* Recognize glob `3*` as a valid version string for CRuby, allowing:
rvm use 3.0.0-preview1 --binary --fuzzy --install
```sh-session
$ rvm use 3.0.0-preview1 --binary --fuzzy --install
Unknown ruby interpreter version (do not know how to handle): 3.0.0-preview1.
```
```sh-session
$ rvm use 3.0.0-preview1 --binary --fuzzy --install
Required ruby-3.0.0-preview1 is not installed - installing.
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-3.0.0-preview1.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-3.0.0-preview1 - #configure
ruby-3.0.0-preview1 - #download
% Total    % Received % Xferd  Average Speed   Time    Time …
```
=> Recognize `3*` as CRuby version number

CHANGELOG.md, scripts/functions/requirements/ubuntu
Fixes #4996 
* Use libssl-1.0 to install Ree 1.8 on Ubuntu
=> Added libssl dependency also to ree 1.8

HACKING.md
Fix usage of `gr` alias for `git remote`.
=> Fix usage of gr alias for git remote

CHANGELOG.md, help/gemset.md, help/index.txt, man/man1/rvm.1, scripts/cli, scripts/extras/completion.bash, scripts/functions/manage/base, scripts/gemsets
* Alias `rvm gemset remove` as `rvm gemset delete`
* Alias `rvm gemset move` as `rvm gemset rename`
* Alias `rvm delete` as `rvm remove`
=> Add few built-in command aliases to improve consistency

CHANGELOG.md, scripts/functions/requirements/fedora, scripts/functions/requirements/fedora_dnf, scripts/functions/requirements/fedora_yum
=> Requirement glibc-headers obsolete on Fedora 33

scripts/functions/installer
Fix bug on fresh installs originated by https://github.com/rvm/rvm/pull/5027 . 
The PR https://github.com/rvm/rvm/pull/5027 fixed ruby3 installation on already installed rvms, but breaks new installations of rvm. So, this PR maintains the fix of https://github.com/rvm/rvm/pull/5027, and also fix the break of new installations.
Feedback of bug provided by @teeigeryuh 🤝 
To test this PR, you can use the following command below: `curl -ksSL https://get.rvm.io | bash -s -- --source github.com/pedrofurtado/rvm` 
Now RVM installs like a charm 🌟 !
@pkuczynski @mpapis Your review on this will be awesome 🍹
=> Fix fresh installs of RVM

HACKING.md
Replace deprecated test instructions in documentation.
According to https://github.com/rvm/rvm-test/blob/master/README.md the rvm-test repository is no longer used.
The `docs/vm_tests.md` was removed.
Note that the document still references `rvm-test` as a source for information on how to write new tests.
=> Replace deprecated test instructions in HACKING.md

CHANGELOG.md, scripts/functions/gemset
Fixes #5025 . Thanks for reporting, @BrianHawley! 🤝 
I believe that is the last part of a series of fixes (https://github.com/rvm/rvm/pull/5029, https://github.com/rvm/rvm/pull/5027) in rvm codebase, to allow ruby v3 + rubygems v3.2.3 inside it without errors.
Steps for testing:
```
$ curl -ksSL https://get.rvm.io | bash -s -- --branch issue-5025
$ source /etc/profile.d/rvm.sh
$ rvm install 3.0.0
$ ruby -v
$ rvm -v
and also for ruby 2.x ...
$ rvm install 2.7.2
$ rvm install 2.5.1
and so on ...
🎉 🎉 
```
=> Fix ruby 3 installation+compilation with rubygems v3.2.3+

CHANGELOG.md, scripts/functions/selector_parse
When installing or selecting a partial ruby spec like ruby-2, it should
get the latest version of that type of ruby. Instead, it was getting
the latest version of the alphabetically last type of ruby that had that
sequence of characters in its version string. The alphabetically last
ruby variant with "ruby" in its name is "truffleruby".
The problem was that the rvm_ruby_interpreter part of the version search
was missing a `^` anchor to indicate the start of the string. Adding that
anchor fixes the search.
This should also fix other occastions where you could select a partial
ruby spec, like rvm use or do.
I also fixed a similar problem with the `--fuzzy` option which made it
find jruby, mruby, or truffleruby, when searching for ruby. This made
rvm …
=> Be more specific about selecting a ruby variant

CHANGELOG.md, scripts/functions/requirements/termux
RVM on Termux was waiting during its requirements install for
user input in a background prompt. The pkg command, based on apt,
had no option to make it accept that prompt automatically, so I
switched the operations to use apt-get, which had such options.
Also, went through the requirements lists and made the lists more
specific for various ruby types. Some ruby types won't work.
=> Fix Termux requirements

CHANGELOG.md, scripts/functions/requirements/osx_brew
`brew search` now takes a mandatory search criteria parameter. It can
return extra entries from the taps, so we still need to grep to make
sure the correct formula is there.
Fixes #5086.
=> Fix invalid brew syntax on requirements check

CHANGELOG.md, scripts/functions/build
* Adds ruby 3 as an allowed ruby to install ruby-head with.
* Be more specific about checking MRI rubies to exclude non-MRI rubies with the MRI ruby prefix somewhere in the version string.
Fixes #5112.
=> Install ruby-head with ruby 3

.github/workflows/specs.yml, CHANGELOG.md, scripts/functions/build_config, tests/long/ruby_prepare_mount_comment_test.sh
* Move remote_comment_test.sh out of fast and don't run it on macOS.
* Make sure that the Ruby used in the prepare test is --movable.
* Update the Darwin rvm_movable_flag version check to include Ruby 3.
Fixes #5118.
=> Fix CI for macOS

CHANGELOG.md, scripts/functions/detect/system_name/os_release
Newer versions of SUSE no longer use /etc/suse-release.
Adding a check in /etc/os-release.
Fixes #5131 .
* Update detection for SLES 15.
=> Fix detection for SUSE 15

scripts/functions/cli
The keyserver `hkp://pool.sks-keyservers.net` has been deprecated. https://unix.stackexchange.com/questions/656205/sks-keyservers-gone-what-to-use-instead
Fixes # .
*
*
*
=> Update keyserver in the docs

config/db
Stable was never updated to point at the 9.3 line, so here it is.
=> Switch default JRuby to 9.3.1.0

CHANGELOG.md, patchsets/ruby/2.6.9/railsexpress, patchsets/ruby/2.6/head/railsexpress, patchsets/ruby/2.7.5/railsexpress, patchsets/ruby/2.7/head/railsexpress, patchsets/ruby/3.0.3/railsexpress, patchsets/ruby/3.0/head/railsexpress
Please merge to add railsexpress patches for 2.6.9, 2.7.5 and 3.0.3.
=> railsexpress patches for 2.6.9, 2.7.5 and 3.0.3

CHANGELOG.md, scripts/functions/pkg
* Avoids duplicate package instances returned by pkg-config
=> Avoid duplicate package instances when querying pkg-config

CHANGELOG.md, patchsets/ruby/3.1.0/railsexpress, patchsets/ruby/3.1/head/railsexpress
=> Remove an obsolete patch from the railsexpress patches for Ruby3.1

CHANGELOG.md, patchsets/ruby/2.7.6/railsexpress, patchsets/ruby/3.0.4/railsexpress, patchsets/ruby/3.1.2/railsexpress
This PR adds railsexpress patches for Ruby 3.1.2, 3.0.4 and 2.7.6
=> Railsexpress patches for ruby 3.1.2, 3.0.4 and 2.7.6

CHANGELOG.md, scripts/functions/requirements/void
We require LibreSSL on Void Linux, but Void dropped Libre to return to OpenSSL last year:
https://voidlinux.org/news/2021/02/OpenSSL.html
Switching the dependency to OpenSSL.
=> Use openssl on Void Linux

CHANGELOG.md, patchsets/ruby/3.2.0/railsexpress, patchsets/ruby/3.2/head/railsexpress
Can you please merge this after I have added the CHANGELOG entry which I can only do after having created the PR because only then I know the correct PR number?
Thx a lot.
=> added railsexpress patches for ruby 3.2

CHANGELOG.md, scripts/rvm
The `GEM_PATH` is set to an empty string by bundler when it is used per
```
bundle install --path vendor/bundle
```
This is intentionally and checked in bundler's specs. See: https://github.com/rubygems/rubygems/blob/77686d0c4c8ffdbcbb8631878eebd0651ed8f90c/bundler/spec/bundler/bundler_spec.rb#L173-L177
However rvm then shows a warning, which is very misleading, since it points to an issue, which is not present at all. Also the warning can turn into a hard error, when the output is used from a subshell. For instance libusb's "make install" fails then, because of "garbage" in the shell output.
> Make sure that your pull request includes entry in the [CHANGELOG](CHANGELOG.md).
This often leads to merge conflicts, so that I didn't add it now. If this PR is OK, then I'll add a CHANGELOG …
=> Don't warn about empty GEM_PATH

CHANGELOG.md, patchsets/ruby/3.2.0/railsexpress, patchsets/ruby/3.2.1/railsexpress, patchsets/ruby/3.2/head/railsexpress
Changes in the MacOS linker and how it is used in ruby 3.2 sometimes lead to failed compiles.
This patch works around the problem.
=> Add a patch to fix erratic linker behavior on macOS

CHANGELOG.md, scripts/functions/selector_interpreters
Ubuntu 18.04 will be end of life soon and TruffleRuby will stop delivering builds based on 18.04 accordingly.
Fixes #5321.
* Change the _truffleruby-dev_ install tarball from one based on Ubuntu 18.04 to one based on Ubuntu 20.04.
=> Update truffleruby-dev to use builds based on Ubuntu 20.04

CHANGELOG.md, gemsets/ruby/3.0.6/global.gems
Related to https://github.com/rvm/rvm/pull/5309
* added missing file
=> Install openssl gem for Ruby 3.0.6

scripts/functions/selector_interpreters
* When installing on an M1 macbook pro, the platform was coming through as macos, so the truffleruby checks did not identify a valid artifact id. That results in the url being invalid and the install failing
* Adding `macos-amd64` and `macos-aarch64` to the case statement with identical artifact ids to their `darwin` counterparts fixes the issue, and truffleruby installs correctly @eregon 
> Make sure that your pull request includes entry in the [CHANGELOG](CHANGELOG.md).
It's not clear to me where I would put an entry in the changelog, or how I would format it, but I am happy to add one! Also happy to add a spec, but it's unclear how i'd do that or what i'd test.
Thanks!
=> Fix truffleruby-23.0.0 installation on macos

CHANGELOG.md, patchsets/ruby/3.3.0/railsexpress, patchsets/ruby/3.3/head/railsexpress
As per usual, railsexpress patches for the newly released ruby.
=> Railsexpress patches for ruby 3.3.0 and 3.3-head

CHANGELOG.md, scripts/functions/selector_interpreters
=> Fix URL for truffleruby-head on darwin-aarch64

.github/workflows/specs.yml, scripts/functions/requirements/osx_brew
It was disabled in https://github.com/rvm/rvm/pull/5119
and means this bug was not caught: https://github.com/rvm/rvm/pull/5385
=> Fixing macOS CI and re-enable the truffleruby test on macOS

CHANGELOG.md, patches/ruby/3.3.1/fix_bootsnap.patch, patchsets/ruby/3.3.1/default
Fixes https://bugs.ruby-lang.org/issues/20450.
* Add a minimalist patch that fixes a bug that prevents Ruby 3.3.1 from working with the Bootsnap gem, which ships with Rails.
=> Add a default patch to fix Bootsnap for Ruby 3.3.1

.github/workflows/gpg_signature.yml, .github/workflows/specs.yml, CHANGELOG.md, tests/long/truffleruby_comment_test.sh
I changed the `actions/checkout` version because it was outdated.
I also noticed that we still had a problem with failing tests, so I tried to fix it.
If the proposed change with TruffleRuby versions is not ok, I can remove it.
Updated: 
CI testing goes further. Now they fail on `tests/fast/do_comment_test.sh`
=> Upgrade github actions and truffleruby version in CI

.github/workflows/specs.yml
From https://github.com/rvm/rvm/pull/5456#discussion_r1581791227
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories
shows macos-14 (M1) is what `macos-latest` resolves to now.
=> Try to fix macOS CI by pinning to a AMD64 macOS image

.github/workflows/specs.yml, CHANGELOG.md
CI tests take a long time because they run different cases one after the other. If something fails, no further tests will be run. ~CI tests have not been passed for some time now. Fast tests didn't pass on CI for MacOS. This change is intended to help us solve this problem more easily.~
* split a long-running tests job into smaller jobs that can be parallelized
The total CI execution time is the same, but the waiting time for the test results is shorter.
=> Parallelize GitHub Action jobs in CI

CHANGELOG.md, patchsets/ruby/3.0.7/railsexpress, patchsets/ruby/3.1.5/railsexpress, patchsets/ruby/3.2.4/railsexpress, patchsets/ruby/3.3.1/railsexpress
Just the usual updates for new rubies.
=> add railsexpress patches for 3.0.7, 3.1.5, 3.2.4 and 3.3.1

CHANGELOG.md, scripts/functions/requirements/solus
Listing all installed packages can be slow with many packages installed.
Asking for specific package is an order of magnitude faster, overall
resulting in >25x improvement on my machine.
Some benchmark results:
```
~ $ time (eopkg info --no-color -s pkgconf | __rvm_grep "^\[inst\][[:space:]]\+pkgconf" > /dev/null 2>&1)
real	0m0.236s
user	0m0.155s
sys	0m0.089s
~ $ time (eopkg li --no-color | __rvm_grep "^pkgconf[[:space:]]\+" > /dev/null 2>&1)
real	0m6.075s
user	0m5.026s
sys	0m0.470s
~ $ # before
~ $ time rvm install 3.3.0
Searching for binary rubies, this might take some time.
No binary rubies available for: solus/4.5/x86_64/ruby-3.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for solus.
Requirements …
```
=> Speed up requirements check on Solus

CHANGELOG.md, scripts/functions/requirements/solus
Solus migrated from pkg-config to the more modern pkgconf, s.
https://github.com/getsolus/packages/commit/0949eab4adfffebb988fd0c8448c52fcddd82969#diff-6da1d22dcf408888f8aa5336844f716dd18fac4d39c0be32f5011b9828a6af53R35-R37
=> Use pkgconf instead of pkg-config in Solus

CHANGELOG.md, scripts/functions/requirements/debian, scripts/functions/requirements/deepin, scripts/functions/requirements/devuan, scripts/functions/requirements/elementary, scripts/functions/requirements/kali, scripts/functions/requirements/mint, scripts/functions/requirements/trisquel, scripts/functions/requirements/ubuntu
I tested this on Ubuntu Noble, Ubuntu Focal, Debian Bookworm, Debian testing (future Trixie), and Debian unstable, and I could install Ruby 3.3 on all systems. I couldn't test all the other distributions, but this shouldn't break anything that wasn't broken before.
This technically doesn't work on Debian testing/unstable, as the numeric version number detection doesn't work, and instead it just discovers the version number as `trixie_sid`, but the old package is still aliased, so installing it works just fine. This will need adjustment when Trixie is released, but that's not going to happen tomorrow.
This fixes #5475.
=> Add support for unversioned libncurses-dev packages on newer Debian-like systems

CHANGELOG.md, scripts/functions/requirements/fedora, scripts/functions/requirements/fedora_dnf
I did not touch `yum` for Fedora, because that is shared with CentOS (which is dead and I can't test), and newer Fedora versions default to `dnf` anyway.
Fixes #5478.
=> Fix zlib packages for Fedora 40+

.github/workflows/specs.yml, CHANGELOG.md, scripts/functions/requirements/osx_brew
When OSX has both openssl@1.1 and openssl@3 installed, the rvm tries to use 1.1
Fixes #5445, #5444, #5180, #5448, #5422, #5393, #5379, #5367, #5365, #5365, #5278, #5272, #5266, #5261, #5246, #5240, #5229, #5222, #5202, #5152, #5039, #5043, #5047, #5408, #4966
=> Require openssl@3 for Ruby 3.2 and 3.3

CHANGELOG.md, scripts/functions/build_config
Fixes #4945.
* ARM support for `__rvm_detect_max_threads` in `scripts/functions/build_config`
Explanation:
> The issue you're encountering is likely due to the fact that the `/proc/cpuinfo` file on ARM architectures doesn't contain the same details (like `vendor_id`) that you would expect on x86-based systems. The existing code depends on finding the `vendor_id` in `/proc/cpuinfo`, which is common on x86 processors but not necessarily present on ARM or other architectures.
> 
> Here's what you can do to modify the function to work better across different architectures, including ARM:
> 
> Use `nproc` Command: The `nproc` command typically provides the number of available processing units and works on most platforms, including ARM.
> 
> Fallback to …
=> Detect core count on ARM machines

CHANGELOG.md, scripts/functions/requirements/ubuntu
Fix a wrongly named method (`requirements_debian_define_libncurses` -> `requirements_ubuntu_define_libncurses`). I think this was a copy/paste error from #5477.
Fixes this error:
```
$ rvm requirements
Checking requirements for ubuntu.
/usr/local/rvm/scripts/functions/requirements/debian: line 139: requirements_ubuntu_define_libncurses: command not found
Requirements installation successful.
```
=> Fix requirement check for Ubuntu

CHANGELOG.md, scripts/functions/requirements/osx_brew
The previous location is giving a 404: https://raw.githubusercontent.com/Homebrew/install/master/install
It needs `.sh` on the end: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
=> Update location of homebrew install script on osx

CHANGELOG.md, scripts/functions/requirements/osx_brew
We've had a couple of Workbrew users with issues with this RVM check so I figured I'd make a PR. If you'd rather not accept it: no worries.
If Workbrew is installed, it's expected that the Homebrew cellar is not writable by the current user. `brew install <foo>` will still work in this environment, though.
Will add a `CHANGELOG.md` entry if you're 👍🏻.
=> Fix detection of Homebrew's write permissions when using Workbrew
