- scripts/functions/rvmrc
- scripts/functions/rvmrc_project
> make sourcing rvmrc work again

- scripts/functions/requirements/freebsd
And start to warn that FreeBSD 10 and up is what rvm supports best.
> Better support rbx under FreeBSD 10

- scripts/functions/requirements/osx_brew
- scripts/functions/requirements/osx_fink
- scripts/functions/requirements/osx_port
> Bump GCC version from 4.8 to 4.9 for OS X 10.10+

- patchsets/ruby/2.2.0/railsexpress
- patchsets/ruby/2.2.1/railsexpress
> Railsexpress patches for ruby 2.2.1

- scripts/functions/environment
I have done as was asked in #3262, however I couldn't get https://github.com/wayneeseguin/rvm-test to work properly.
Also, I have no idea for how to actually and properly test this change.
I did however take the liberty to rename the signal numbers into their actual names, making it a bit more readable to the human eye.
> Fix trap behavior

- patches/ruby/2.2.2/fix_installing_bundled_gems.patch
- patchsets/ruby/2.2.2/default
This is a port of a58579f5360a7922f75fe0e0772d80baf6ef1243
> Add fix_installing_bundled_gems patch for Ruby 2.2.2

- patchsets/ruby/2.0.0/p645/railsexpress
- patchsets/ruby/2.1.6/railsexpress
- patchsets/ruby/2.2.2/railsexpress
could you please merge to master?
> added railsexpress patch sets for the latest ruby versions: 2.2.2, 2.1.6 and 2.0.0-p645

- config/known
- config/known_strings
- config/md5
- config/sha512
> Updated for JRuby 9.0.0.0

- scripts/functions/detect_system
- scripts/functions/requirements/devuan
This is a pull request of @aleskandro's patch from #3482.
Closes #3482.
> Added support for Devuan (@aleskandro's patch).

- patchsets/ruby/2.0.0/p647/railsexpress
- patchsets/ruby/2.1.7/railsexpress
- patchsets/ruby/2.2.3/railsexpress
added railsexpress patches for all recently released rubies.
> added railsexpress patches for all recently released rubies

- bin/rvm-prompt
- scripts/cd
- scripts/functions/env
- scripts/functions/installer
- scripts/gemsets
Found and fixed a few typos in the comments.
> Fixed some typos.

- README
32 bit flag exists but is not documented yet as per this issue: https://github.com/rvm/rvm/issues/623
> Update README with --32 bit flag

- config/known
- config/known_strings
- config/md5
- config/sha512
31 issues fixed for 1.7.23.
[1] http://jruby.org/2015/11/24/jruby-1-7-23.html
> Add support for JRuby 1.7.23 [1]

- patches/ruby/2.2.4/fix_installing_bundled_gems.patch
- patchsets/ruby/2.2.4/default
> Add fix_installing_bundled_gems patch for 2.2.4

- scripts/functions/requirements/openmandriva
recognize aarch64 as 64-bit arch too.
> Update openmandriva aarch64 as 64bit arch

- scripts/functions/environment
> Bug with bash sessions on OSX 10.11+

- scripts/functions/environment
shell_session_update not found when ~/.bash_sessions_disable exists
Signed-off-by: feng xiahou xiahoufeng@yahoo.com
> should deal with ~/.bash_sessions_disable

- scripts/functions/requirements/openbsd
The currently referenced mirror is no longer available.
> Reference an available mirror

- patchsets/ruby/2.2.5/railsexpress
- patchsets/ruby/2.3.1/railsexpress
> added rails express patches for 2.2.5 and 2.3.1

- scripts/functions/rvmrc_warning
> improve warning display message

- help/prepare.md
- scripts/prepare
- update-remote.sh
> Fixing rvm.io ssh path (#3692)

- scripts/functions/requirements/ubuntu
> Adding jdk8 to ubuntu requirements (#3719)

- scripts/functions/detect_system
- scripts/functions/requirements/solus
Just a small patch to add support for Solus linux.
> Add support for Solus linux

- config/md5
- config/remote
- config/sha512
> Adding 2.3.3 to Ubuntu x64 (#3820)

- .github/ISSUE_TEMPLATE.md
> Fix typos, grammar, and Markdown syntax

- patchsets/ruby/2.3.3/railsexpress
I have updated the railsexpress patches to support the recently released ruby 2.3.3. Can you please merge?
> added railsexpress patches for ruby-2.3.3

- scripts/functions/installer
> Add comment about rvm PATH being the las

- CHANGELOG.md
- scripts/functions/requirements/arch
> Cannot build rbx-2.5.2 on ArchLinux

- CHANGELOG.md
- config/md5
- config/remote
- config/sha512
> Adding Ubuntu x64 binary for Ruby 2.4.0 (#3867)

- CHANGELOG.md
- scripts/functions/cli
> Mention in PATH warnings about ability to silence them

- CHANGELOG.md
- scripts/functions/requirements/cygwin
> Missing cygwin32-readline package on Windows

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> Warning: openssl is a keg-only and another version is linked to opt

- CHANGELOG.md
- config/db
- scripts/functions/detect_system
- scripts/functions/requirements/pclinuxos
- scripts/functions/support
> Missing libyaml-devel on PCLinuxOS 64-bit

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> Fix openssl version for ruby 1.8 on OSX #3954

- CHANGELOG.md
- config/md5
- config/remote
- config/sha512
> Ubuntu x64 binary for Ruby 2.4.1 (#3965)

- CHANGELOG.md
- config/md5
- config/remote
- config/sha512
Fixes #3985.
Binary already uploaded.
> Adding ruby 2.3.4 binnary for Ubuntu 16.04 x64 (#3985)

- CHANGELOG.md
- scripts/functions/environment
> Do not unset rvm_pretty_print_flag

- CHANGELOG.md
- scripts/completion
- scripts/extras/completion.bash
Improve Bash shell completion for RVM commands
> Improve Bash completion

- CHANGELOG.md
- patchsets/ruby/2.3.4/railsexpress
Patches for 2.3.4 and 2.3-head
> added railsexpress patches for ruby 2.3.4

- FORMATTING.md
An attempt to improve the phrasing without altering the meaning.
> Alter phrasing in FORMATTING.md

- scripts/functions/version
Fixes #4072 . Code is added to scripts/functions/version now because of changes in #4117 .
> Recreate 'rvm version' command

- CHANGELOG.md
- scripts/functions/utility
Fixes #4009.
Add warning for sudo users
> Add warning for sudo users, fix #4009

- CHANGELOG.md
- scripts/hook
Fixes #3902.
Ensure rvm_hooks_path is set
> Ensure rvm_hooks_path is set

- CHANGELOG.md
- patchsets/ruby/2.2.6/railsexpress
- patchsets/ruby/2.2.7/railsexpress
Patch adds railsexpress patches for 2.2.6 and 2.2.7
> please add railsexpress patches for 2.2.6 and 2.2.7

- CHANGELOG.md
- scripts/irbrc.rb
Fixes #4158, update 44b7654950cd9e5fa2b6704aae7b90fcbb8625ee (#3969)
> Set back IRB history default to HOME

- CHANGELOG.md
- scripts/functions/build_config
Reported in https://github.com/rvm/rvm/issues/4007#issuecomment-328446230
> Improved CPU count detection, related to #4007

- scripts/functions/requirements/debian
Just a minor thing to standardize the code
> Use `rvm_version_compare` to compare system versions

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> ree-1.8.7 requires old version of OpenSSL 1.0.2

- CHANGELOG.md
- scripts/functions/detect_systems/debian_codenames
> Add support for Debian Buster (10)

- CHANGELOG.md
- scripts/functions/requirements/fedora
- scripts/functions/requirements/fedora_dnf
- scripts/functions/requirements/fedora_yum
> Implement DNF package manager for Fedora 22+

- docs/gpg.md
non code change, no changelog update
> Add gpg and refresh contributing docs

- CHANGELOG.md
- scripts/functions/requirements/opensuse
- scripts/functions/requirements/suse
> Add openSUSE 15 support

- CHANGELOG.md
- README.md
*  Update README including Table of Contents to help improve documentation readability
Let me know if I missed anything, thanks for the great work :)
> Add "Table of Contents" to README.md

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> Drop homebrew/versions and upgrade gcc to 6.0

- CHANGELOG.md
- scripts/functions/requirements/centos
- scripts/functions/requirements/fedora_dnf
- scripts/functions/requirements/fedora_yum
Based on: https://book.rubinius.com/manuscript/getting_rubinius.html
> Add support for installing Rubinius on Redhat/Fedora

- CHANGELOG.md
- scripts/functions/rvmrc_project
closes #4314 - needed to rebase to fix tests and confirm it actually works
> Fix project file reject reason in bash -e

- examples/rvmrc
* Fixing typo in the sample nvmrc
> Fix "feature" typo

- CHANGELOG.md
- patchsets/ruby/2.3.8/railsexpress
- patchsets/ruby/2.4.5/railsexpress
- patchsets/ruby/2.5.3/railsexpress
railsexpress updates for the latest ruby releases
> railsexpress updates for the latest ruby releases

- CHANGELOG.md
- scripts/functions/requirements/mint
> Fix libssl dependency for Mint 19

- CHANGELOG.md
- scripts/functions/detect_systems/os_release
- scripts/functions/requirements/elementary
- scripts/functions/requirements/void
Fixes #4472 
Includes #4483 which should be merged first.
> Add support for Void linux

- CHANGELOG.md
- scripts/functions/gemset
> Use --no-ri or --no-document depending on ruby version

- CHANGELOG.md
- scripts/functions/utility_system
- scripts/rvm
> Add support for MINGW in main rvm script

- CHANGELOG.md
- scripts/functions/requirements/mint
> Fix Linux Mint 19 dependencies

- CHANGELOG.md
- scripts/functions/cli
> Fix return code in signature check function (#4530)

- CHANGELOG.md
- scripts/functions/version
Fixes https://github.com/rvm/rvm/issues/4521#issuecomment-447939769
> Check `stable` branch to establish the latest version

- CHANGELOG.md
- patchsets/ruby/2.6.0/railsexpress
- patchsets/ruby/2.6/head/railsexpress
Can you please merge once I've added the change log entry?
Thx a lot.
> added railsexpress patches for 2.6.0 and 2.6-head

- CHANGELOG.md
- scripts/functions/detect/system
- scripts/functions/detect/system_name/os_release
Fixes https://github.com/rvm/rvm1-ansible/issues/181
> Improve detection of Amazon Linux 2

- scripts/functions/notes/opencollective
- scripts/notes
Let users know they can donate on open collective...
> Add open collective note

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> Add missing zlib dependency for macOS

- update-truffleruby.rb
> Automatically add a ChangeLog entry with update-truffleruby.rb

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
> Fix installing Homebrew in a custom location

- CHANGELOG.md
- patchsets/ruby/2.5.4/railsexpress
- patchsets/ruby/2.6.2/railsexpress
> Railsexpress patches for ruby 2.5.4 and 2.6.2

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
Base on https://book.rubinius.com/manuscript/getting_rubinius.html
> Update rbx dependencies for macOS

- CHANGELOG.md
- patchsets/ruby/2.5.5/railsexpress
> added railsexpress patches for ruby 2.5.5

- scripts/functions/cli
Provide the user the commands for the typical next steps.
Fixes #4695.
Added CHANGELOG entry. If that is really wished even for tiny changes like this, give me feedback (I will then also update the CONTRIBUTING (ater opening an issue ;) ), as this policy is not mentioned there).
> Improve CLI error messages/warnings (#4695)

- CHANGELOG.md
- patchsets/ruby/2.6.3/railsexpress
> added railsexpress patches for Ruby 2.6.3

- CHANGELOG.md
- scripts/functions/detect/system
- scripts/functions/requirements/termux
- scripts/rvm
> Add Termux support

- CHANGELOG.md
- scripts/functions/detect/system
- scripts/functions/requirements/termux
- scripts/rvm
Fixes #4734
Fixes bad merge in #4749
> Add Termux support #4749

- bin/rvmsudo
- scripts/extras/chruby.sh
- scripts/extras/completion.bash
- scripts/functions/build_config_system
- scripts/functions/manage/ree
- scripts/functions/requirements/netbsd
- scripts/functions/requirements/osx_brew
- scripts/info
- scripts/maglev
- scripts/mount
> Implement new __rvm_ls across the whole app

- CHANGELOG.md
- patchsets/ruby/2.7.0/railsexpress
- patchsets/ruby/2.7/head/railsexpress
New patchsets for 2.7.
Can you please merge?
> added railsexpress patches for 2.7

- CHANGELOG.md
- scripts/functions/manage/opal
This seems to be more reasonable approach...
> Install Opal globally

- .github/mergeable.yml
Follows suggestion from https://github.com/mergeability/mergeable/issues/285
> Fix mergeable settings failing the PR

- CHANGELOG.md
- patchsets/ruby/2.7.2/railsexpress
This adds railsexpress patches for 2.7.2
> added rails express patches for 2.7.2

- .github/mergeable.yml
- CHANGELOG.md
> Fix broken mergeable config

- CHANGELOG.md
- scripts/functions/requirements/osx_brew
The version check used on #4995 can be improved with a simpler AWK command, merging 3 commands into one.
> Use AWK to check Brew version

- CHANGELOG.md
- patchsets/ruby/3.0.0/railsexpress
- patchsets/ruby/3.0/head/railsexpress
Just the usual railsexpress updates.
> added rails express patches for 3.0.0 and 3.0-head

- CHANGELOG.md
- contrib/ps1_functions
* Update the `ps1_functions` helper to correctly identify the `main` branch
> Updated colours to support the `main` branch

- README.md
Fixed typos and altered wording for readability. Updated year as well.
> Typo and grammatical fixes in README

- CHANGELOG.md
- patchsets/ruby/2.6.7/railsexpress
- patchsets/ruby/2.7.3/railsexpress
- patchsets/ruby/3.0.1/railsexpress
CHANGELOG update will follow once I know the number.
> added railsexpress patches for 2.6.7, 2.7.3 and 3.0.1

- .github/workflows/gpg_signature.yml
- .github/workflows/specs.yml
Follow-up of #5040
cc @pedrofurtado
> Improve GitHub Actions

- README.md
> Github actions badges in README.md

- .github/workflows/specs.yml
- tests/fast/alias_comment_test.sh
- tests/fast/current_and_list_comment_test.sh
- tests/fast/do_comment_test.sh
- tests/fast/gem-bundle_comment_test.sh
- tests/fast/gemfile_comment_test.sh
- tests/fast/gemsets_comment_test.sh
- tests/fast/globalcache_comment_test.sh
- tests/fast/load_ruby-version_comment_test.sh
- tests/fast/remote_comment_test.sh
- tests/fast/ruby-version_comment_test.sh
- tests/fast/rvm-prompt_comment_test.sh
- tests/fast/rvm-shell_comment_test.sh
- tests/fast/rvmrc-create_comment_test.sh
- tests/fast/use_comment_test.sh
- tests/fast/versions.conf_comment_test.sh
- tests/fast/wrapper_comment_test.sh
- tests/long/named_ruby_and_gemsets_comment_test.sh
Follow-up of #5104, and ref #5038.
CI passes on Linux now: https://github.com/eregon/rvm/actions/runs/1053563216
Let's see how it goes on macOS.
> Fix GitHub Actions CI

- CHANGELOG.md
- patchsets/ruby/2.6.8/railsexpress
- patchsets/ruby/2.7.4/railsexpress
- patchsets/ruby/3.0.2/railsexpress
Just the usual railsexpress updates. Can you please review and merge?
> added rails express patches for MRI 2.6.8, 2.7.4 and 3.0.2

- CHANGELOG.md
- patchsets/ruby/3.1.0/railsexpress
- patchsets/ruby/3.1/head/railsexpress
railsexpress patches for Ruby 3.1
> added railsexpress patches for 3.1 release branch

- CHANGELOG.md
- scripts/functions/requirements/devuan
> Use libreadline-dev instead of libreadline6-dev on Devuan 2

- CHANGELOG.md
- patchsets/ruby/2.7.7/railsexpress
- patchsets/ruby/2.7/head/railsexpress
- patchsets/ruby/3.0.5/railsexpress
- patchsets/ruby/3.0/head/railsexpress
- patchsets/ruby/3.1.3/railsexpress
added new railsexpress patches
> rails express patch updates

- CHANGELOG.md
- patchsets/ruby/3.2.1/railsexpress
Added railsexpress patches for ruby 3.2.1.
> added railsexpress patches for ruby 3.2.1

- CHANGELOG.md
- patchsets/ruby/3.2.3/railsexpress
- patchsets/ruby/3.3.0/railsexpress
Added railsexpress patches for Ruby 3.2.3
> Rails express patches for ruby 3.2.3

- README.md
* Improve formatting of curl install command in README
> Improve formatting of curl install command

- .github/actions/test/action.yml
- .github/workflows/specs.yml
- tests/jruby/jruby_comment_test.sh
- tests/truffleruby/truffleruby_comment_test.sh
Fix test matrix broken in #5542
> ci: fix test matrix
